version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    qutemap:
        level: DEBUG
        handlers: [console]
        propagate: no
    scheme:
        level: DEBUG
        handlers: [console]
        propagate: no
    js:
        level: DEBUG
        handlers: [console]
        propagate: no
    qt:
        level: DEBUG
        handlers: [console]
        propagate: no
root:
    level: DEBUG
    handlers: [console]